### ISSUE TITLE
Issue in the table heading, the icons for sorting is not rendering properly 

### ISSUE THREAD

**Issue by SouradipAdhikari03** [RayaBasu01/KinaraStudentAPI_UI.github.io#1]
There is issue in the icons of the table

**Comment by PratikMbade** [comment]
@SouradipAdhikari03 describe properly so ,i can work on it.

**Comment by RayaBasu01** [comment]
Sure, Go for it @PratikMbade

**Comment by RayaBasu01** [comment]
@PratikMbade open the link (https://rayabasu01.github.io/StudentAPI_UI.github.io/) you will find that in the table heading the icons beside Roll no, first name, last name, gender dept and cgpa is not showing. It can be updated, and also the UI is not loading properly and in the page no part is not proper.. drop a comment if you need any help

**Comment by SouradipAdhikari03** [comment]
@PratikMbade  open the link (https://rayabasu01.github.io/StudentAPI_UI.github.io/) you will find that in the table heading the icons beside Roll no, first name, last name, gender dept and cgpa is not showing. It can be updated, and also the UI is not loading properly and in the page no part is not proper.. drop a comment if you need any help

**Comment by PratikMbade** [comment]
@SouradipAdhikari03  are you talking about this icons? 
![image](https://github.com/RayaBasu01/StudentAPI_UI.github.io/assets/110896142/036b48ca-f6d1-461b-97a7-7985413ba66d)

**Comment by SouradipAdhikari03** [comment]
@PratikMbade Yes, and if possible the pagination part also....

**Comment by PratikMbade** [comment]
@SouradipAdhikari03 Sure.

**Comment by pulkitxm** [comment]
Can I get assigned? let me know how to start.
